// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jywnmsnwqzvafzprkvep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5d25tc253cXp2YWZ6cHJrdmVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjYxOTMsImV4cCI6MjA2NTc0MjE5M30.K9XquLdInl1Wan2JdnzbyZhkQmy7pJNfDzcvyjsDKAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);